[build]
  command = "# no build"
  publish = "/"  # 점(.) 대신 슬래시(/)를 사용하여 루트임을 명시합니다.

[[headers]]
  for = "/.well-known/pi.toml"
  [headers.values]
    Content-Type = "application/toml"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200